## **Descriptive and Probabilistic Analysis of Air Quality in Yogyakarta, Indonesia (2021)**
- Group Number: 12
- Name:
1. Muhammad Akbar Rizky Hidayat - 5027261032
2. Dhafin Abhinaya Setyawan - 5027261083
3. Jenifer Tri Fena Andhika - 5027261123
- Topic: Smart City

### **Background**
Air quality is one of the key indicators for assessing a city’s sustainability, especially amid the rapid growth of transportation and industrial activities across various regions of Indonesia. The “Air Quality in Yogyakarta, Indonesia (2021)” dataset contains air pollution measurement data for Yogyakarta throughout 2021. Our group chose this dataset because Yogyakarta is one of Indonesia’s major cities with high population and vehicle mobility levels, making the data relevant for providing a general picture of urban air quality. Through descriptive statistics analysis of this data, we aim to illustrate the patterns and levels of air quality in Yogyakarta throughout the year, while connecting them to the Sustainable Development Goals (SDGs), specifically SDG 3 (Good Health and Well-being), as air quality directly impacts public respiratory health, and SDG 11 (Sustainable Cities and Communities) because air quality monitoring is a crucial part of efforts to create safe, inclusive, and sustainable cities. Thus, the results of this analysis are expected to serve as a simple example of how a city’s air quality data can be used to raise awareness and data-driven decision-making toward more sustainable urban development.

### **Questions:**
1. What are the mode, median, mean, range, and variance of PM2.5 and PM10 concentrations in Yogyakarta for each month throughout the year?
2. Which hours of the day show the highest and lowest average pollutant concentrations?
3. What proportion of hours or days fall into each category (Good, Moderate, Unhealthy, Very Unhealthy, Dangerous)?

### **Data Description and Dictionary**

- Source of data: The data comes from the Yogyakarta Environmental Agency (Dinas Lingkungan Hidup Yogyakarta), which was processed and uploaded to Kaggle by Adhang MM at this link: https://www.kaggle.com/datasets/adhang/air-quality-in-yogyakarta-indonesia-2021
- License: Data files © Original Authors
- The data was collected by the Yogyakarta Environmental Agency in April 2021. Measurements were taken hourly. The original pollution values were converted into the Pollutant Standards Index (PSI/ISPU).
- The data has 11 columns for each month.
- January, March, May, July, August, October, and December consist of 744 rows.
- February consists of 674 rows.
- April, June, September, and November consist of 720 rows.

| Column | Definition | Variable Type | Scale | Units | Example |
| --- | --- | --- | --- | --- | --- |
| Date | Date the measurement was taken | Qualitative | Interval | - | 4/1/2021 |
| Time | Time the measurement was taken (hourly) | Qualitative | Interval | - | 00:00:00 | 
| PM2.5 | Particulate Matter 2.5 measurement (Index) | Quantitative Discrete | Ratio | PSI | 45 |
| PM10 | Particulate Matter 10 measurement (Index) | Quantitative Discrete | Ratio | PSI | 19 |
| SO2 | Sulfur Dioxide measurement (Index) | Quantitative Discrete | Ratio | PSI | 15 |
| CO | Carbon Monoxide measurement (Index) | Quantitative Discrete | Ratio | PSI | 15 |
| O3 | Ozone measurement (Index) | Quantitative discrete | Ratio | PSI | 8 |
| NO2 | Nitrogen Dioxide measurement (Index) | Quantitative Discrete | Ratio | PSI | 3 |
| Max | Highest pollution measurement value at that hour | Quantitative Discrete | Ratio | PSI | 45 |
| Critical Component | Gas component contributing to the highest pollution | Qualitative | Nominal | – | PM2.5 |
| Category | Air quality category based on the Max value | Qualitative | Ordinal | – | Good |

### **Yogyakarta's Air Quality Dataset in January 2021**

In [1]:
import pandas as pd

df = pd.read_csv("01-jogja-jan-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(744, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,1/1/2021,00:00:00,13,40,0,25,0,0,40,PM2.5,Good
1,1/1/2021,01:00:00,12,38,0,24,0,0,38,PM2.5,Good
2,1/1/2021,02:00:00,11,35,0,23,0,0,35,PM2.5,Good
3,1/1/2021,03:00:00,10,32,0,22,0,0,32,PM2.5,Good
4,1/1/2021,04:00:00,9,29,0,21,0,0,29,PM2.5,Good

In [2]:
df.info()                 # tipe data setiap kolom
df.isna().sum()           # jumlah data kosong per kolom
df.duplicated().sum()     # jumlah baris duplikat

<class 'pandas.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                744 non-null    str
 1   Time                744 non-null    str
 2   PM10                744 non-null    int64
 3   PM2.5               744 non-null    int64
 4   SO2                 744 non-null    int64
 5   CO                  744 non-null    int64
 6   O3                  744 non-null    int64
 7   NO2                 744 non-null    int64
 8   Max                 744 non-null    int64
 9   Critical Component  744 non-null    str
 10  Category            744 non-null    str
dtypes: int64(7), str(4)
memory usage: 64.1 KB

np.int64(0)

In [3]:
kolom = df["PM2.5"] #hanya bisa diambil dari kolom "numerik"
kolom.mean(), kolom.median(), kolom.mode()[0]
kolom.var(), kolom.std()
kolom.quantile(0.25), kolom.quantile(0.75)
df.describe()

,PM10,PM2.5,SO2,CO,O3,NO2,Max
count,744.000000,744.000000,744.000000,744.000000,744.000000,744.000000,744.000000
mean,16.063172,46.782258,14.005376,24.534946,22.290323,2.469086,48.432796
std,8.358234,18.616724,10.531244,3.355775,17.578254,2.179462,16.666334
min,2.000000,12.000000,0.000000,17.000000,0.000000,0.000000,19.000000
25%,8.000000,30.000000,1.000000,22.000000,0.000000,0.000000,34.000000
50%,16.000000,52.000000,20.000000,25.000000,26.000000,3.000000,52.000000
75%,21.000000,60.000000,23.000000,27.000000,38.000000,4.000000,60.000000
max,35.000000,80.000000,28.000000,33.000000,55.000000,7.000000,80.000000

### **Yogyakarta's Air Quality Dataset in February 2021**

In [4]:
import pandas as pd

df = pd.read_csv("02-jogja-feb-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(672, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,2/1/2021,00:00:00,21,61,18,23,38.0,5,61,PM2.5,Moderate
1,2/1/2021,01:00:00,20,60,18,23,38.0,5,60,PM2.5,Moderate
2,2/1/2021,02:00:00,20,59,18,23,39.0,5,59,PM2.5,Moderate
3,2/1/2021,03:00:00,20,59,18,24,39.0,5,59,PM2.5,Moderate
4,2/1/2021,04:00:00,20,60,18,24,39.0,5,60,PM2.5,Moderate

### **Yogyakarta's Air Quality Dataset in March 2021**

In [5]:
import pandas as pd

df = pd.read_csv("03-jogja-mar-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(744, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,3/1/2021,00:00:00,13,48,19,15,35,6,48,PM2.5,Good
1,3/1/2021,01:00:00,14,51,19,16,36,6,51,PM2.5,Moderate
2,3/1/2021,02:00:00,15,52,20,17,37,6,52,PM2.5,Moderate
3,3/1/2021,03:00:00,16,54,20,17,37,6,54,PM2.5,Moderate
4,3/1/2021,04:00:00,17,55,21,18,38,6,55,PM2.5,Moderate

### **Yogyakarta's Air Quality Dataset in April 2021**

In [6]:
import pandas as pd

df = pd.read_csv("04-jogja-apr-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(720, 11)

,Date,Time,PM2.5,PM10,SO2,CO,O3,NO2,Max,Critical Component,Category
0,4/1/2021,00:00:00,45,19,21,15,8.0,3,21,PM2.5,Good
1,4/1/2021,01:00:00,44,18,20,14,8.0,3,20,PM2.5,Good
2,4/1/2021,02:00:00,43,17,20,14,7.0,3,20,PM2.5,Good
3,4/1/2021,03:00:00,40,17,20,13,7.0,3,20,PM2.5,Good
4,4/1/2021,04:00:00,38,16,19,12,7.0,3,19,PM2.5,Good

### **Yogyakarta's Air Quality Dataset in May 2021**

In [7]:
import pandas as pd

df = pd.read_csv("05-jogja-may-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(744, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,5/1/2021,00:00:00,22,53,17,12,NaN,4,53,PM2.5,Moderate
1,5/1/2021,01:00:00,22,52,17,12,NaN,4,52,PM2.5,Moderate
2,5/1/2021,02:00:00,21,52,17,12,NaN,4,52,PM2.5,Moderate
3,5/1/2021,03:00:00,22,52,17,12,NaN,4,52,PM2.5,Moderate
4,5/1/2021,04:00:00,22,53,17,12,NaN,4,53,PM2.5,Moderate

### **Yogyakarta's Air Quality Dataset in June 2021**

In [8]:
import pandas as pd

df = pd.read_csv("06-jogja-jun-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(720, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,6/1/2021,00:00:00,20,48,21.0,8,14.0,5,48,PM2.5,Good
1,6/1/2021,01:00:00,20,49,21.0,8,14.0,5,49,PM2.5,Good
2,6/1/2021,02:00:00,21,50,21.0,8,14.0,5,50,PM2.5,Good
3,6/1/2021,03:00:00,21,51,21.0,9,15.0,5,51,PM2.5,Moderate
4,6/1/2021,04:00:00,22,51,22.0,9,16.0,5,51,PM2.5,Moderate

### **Yogyakarta's Air Quality Dataset in July 2021**

In [9]:
import pandas as pd

df = pd.read_csv("07-jogja-jul-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(744, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,7/1/2021,00:00:00,35.0,58.0,NaN,11.0,NaN,5.0,58,PM2.5,Moderate
1,7/1/2021,01:00:00,34.0,57.0,NaN,10.0,NaN,5.0,57,PM2.5,Moderate
2,7/1/2021,02:00:00,33.0,57.0,NaN,10.0,NaN,5.0,57,PM2.5,Moderate
3,7/1/2021,03:00:00,32.0,56.0,NaN,10.0,NaN,5.0,56,PM2.5,Moderate
4,7/1/2021,04:00:00,31.0,55.0,NaN,9.0,NaN,5.0,55,PM2.5,Moderate

### **Yogyakarta's Air Quality Dataset in August 2021**

In [10]:
import pandas as pd

df = pd.read_csv("08-jogja-aug-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(744, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,8/1/2021,00:00:00,10.0,24.0,NaN,1.0,NaN,3.0,24,PM2.5,Good
1,8/1/2021,01:00:00,11.0,24.0,NaN,1.0,NaN,3.0,24,PM2.5,Good
2,8/1/2021,02:00:00,11.0,24.0,NaN,1.0,NaN,3.0,24,PM2.5,Good
3,8/1/2021,03:00:00,11.0,24.0,NaN,1.0,NaN,3.0,24,PM2.5,Good
4,8/1/2021,04:00:00,11.0,24.0,NaN,1.0,NaN,3.0,24,PM2.5,Good

### **Yogyakarta's Air Quality Dataset in September 2021**

In [11]:
import pandas as pd

df = pd.read_csv("09-jogja-sep-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(720, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,9/1/2021,00:00:00,16.0,28.0,0.0,7.0,0.0,4.0,28,PM2.5,Good
1,9/1/2021,01:00:00,16.0,28.0,0.0,7.0,0.0,4.0,28,PM2.5,Good
2,9/1/2021,02:00:00,16.0,28.0,0.0,7.0,0.0,4.0,28,PM2.5,Good
3,9/1/2021,03:00:00,18.0,32.0,0.0,7.0,1.0,4.0,32,PM2.5,Good
4,9/1/2021,04:00:00,18.0,32.0,0.0,6.0,1.0,4.0,32,PM2.5,Good

### **Yogyakarta's Air Quality Dataset in October 2021**

In [12]:
import pandas as pd

df = pd.read_csv("10-jogja-oct-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(744, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,10/1/2021,00:00:00,19.0,35.0,0.0,7.0,5.0,4.0,35,PM2.5,Good
1,10/1/2021,01:00:00,19.0,35.0,0.0,7.0,5.0,4.0,35,PM2.5,Good
2,10/1/2021,02:00:00,18.0,34.0,0.0,7.0,6.0,4.0,34,PM2.5,Good
3,10/1/2021,03:00:00,16.0,30.0,0.0,7.0,7.0,4.0,30,PM2.5,Good
4,10/1/2021,04:00:00,16.0,30.0,0.0,7.0,8.0,4.0,30,PM2.5,Good

### **Yogyakarta's Air Quality Dataset in November 2021**

In [13]:
import pandas as pd

df = pd.read_csv("11-jogja-nov-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(720, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,11/1/2021,00:00:00,16.0,29.0,0.0,16.0,0.0,0.0,29,PM2.5,Good
1,11/1/2021,01:00:00,16.0,29.0,0.0,16.0,0.0,0.0,29,PM2.5,Good
2,11/1/2021,02:00:00,16.0,29.0,0.0,16.0,0.0,0.0,29,PM2.5,Good
3,11/1/2021,03:00:00,16.0,29.0,0.0,16.0,0.0,0.0,29,PM2.5,Good
4,11/1/2021,04:00:00,16.0,29.0,0.0,16.0,0.0,0.0,29,PM2.5,Good

### <span style="color:red">**Yogyakarta's Air Quality Dataset in December 2021**</span>

In [14]:
import pandas as pd

df = pd.read_csv("12-jogja-dec-2021.csv")
print(df.shape)  # (jumlah baris, jumlah kolom)
df.head()

(744, 11)

,Date,Time,PM10,PM2.5,SO2,CO,O3,NO2,Max,Critical Component,Category
0,12/1/2021,00:00:00,26.0,38.0,25.0,19.0,36.0,0.0,38,PM2.5,Good
1,12/1/2021,01:00:00,24.0,36.0,24.0,18.0,37.0,0.0,37,O3,Good
2,12/1/2021,02:00:00,23.0,34.0,23.0,18.0,38.0,0.0,38,O3,Good
3,12/1/2021,03:00:00,18.0,31.0,23.0,17.0,39.0,0.0,39,O3,Good
4,12/1/2021,04:00:00,17.0,31.0,22.0,17.0,40.0,0.0,40,O3,Good

<span style="color:red">This is red text</span>